### PR TITLE
Added fallback to password entry

### PR DESCRIPTION
**Pull request by serverwentdown**
This PR adds fallback to password when clicking the "Use password..." button.

### CODE REVIEW

**Review by henrik242 — APPROVED** [review]
LGTM 👍

**Comment by patgmac** [comment]
Is this going to be merged?

**Comment by 19h** [comment]
Please merge

**Comment by serverwentdown** [comment]
@mattrajca?

**Comment by henrik242** [comment]
@serverwentdown Maybe about time to fork and release to homebrew?  It doesn't seem like @mattrajca is active anymore.

**Comment by serverwentdown** [comment]
Yep, seems like @mattrajca isn't active anymore.

**Comment by knu** [comment]
Looks great, and I've pushed this further and made it fall back when Touch ID is not available: https://github.com/serverwentdown/sudo-touchid/pull/1

Software like Near Lock offers local [authentication](https://nearlock.me/features#authentication) via iPhone/Apple Watch, so the bridge between sudo and the LocalAuthentication framework is useful even on MacBooks without Touch ID!

**Comment by serverwentdown** [comment]
@knu Nice, I suppose you have tested it on non-TouchID MacBooks? I don't have mine at hand.

**Comment by knu** [comment]
@serverwentdown Yes, I've tested it on my 12" MacBook (2017) and it works perfectly.  On the other hand I haven't tested it on a MBP with Touch ID because mine just got broken. 😞
Can you confirm that I didn't break anything with regard to Touch ID authentication?

**Comment by serverwentdown** [comment]
@knu Yep, works fine on mine.

**Comment by serverwentdown** [comment]
@henrik242 I'm not really interested in maintaining a homebrew tap... 😢

**Comment by henrik242** [comment]
Maybe @jhochwald is interested instead?

**Comment by samm-git** [comment]
I can maintain homebrew tap. But do we have some repository with all PR included?

**Pull request closed without merging**
